name: learning-haskell
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/learning-haskell

dependencies:
  #- freer-effects
  - QuasiText
  - QuickCheck
  - base >= 4.7 && < 5
  - cmdargs
  - conduit
  - conduit-extra
  - connection
  - data-default
  - extensible
  - extensible-effects
  - free
  - ghc-prim
  - here
  - http-client
  - http-conduit
  - idris
  - interpolate
  - lens
  - lens-regex
  - mtl
  - parsers
  - raw-strings-qq
  - regex-posix
  - rio
  - safe-exceptions
  - singleton-bool
  - singletons
  - string-qq
  - suspend
  - time-out
  - time-units
  - timers
  - transformers
  - trifecta
  - unliftio

executables:
  # stack build --profile && stack exec ghc-callstack
  ghc-callstack:
    source-dirs: GHC/Stack
    main: Main.hs
