name: learning-haskell
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/learning-haskell

dependencies:
  - QuasiText
  - QuickCheck
  - base >= 4.7 && < 5
  - cmdargs
  - conduit
  - conduit-extra
  - connection
  - data-default
  - extensible
  - extensible-effects
  - free
  - freer-effects
  - ghc-prim
  - here
  - http-client
  - http-conduit
  - interpolate
  - lens
  - lens-regex
  - mtl
  - raw-strings-qq
  - regex-posix
  - safe-exceptions
  - singleton-bool
  - singletons
  - string-qq
  - suspend
  - time-out
  - time-units
  - timers
  - transformers

executables:
  fake:
    main: Main.hs
    source-dirs: .
